---
title: XVII Jornada das Estrelas
date: 27 05 24
category: "Próximo" 
format:
    html:
        include-in-header:
            text: |
                <link href="https://unpkg.com/tabulator-tables@6.2.1/dist/css/tabulator.min.css" rel="stylesheet"> <script type="text/javascript" src="https://unpkg.com/tabulator-tables@6.2.1/dist/js/tabulator.min.js"></script>
---

Entre os dias 18/06/24 e 20/06/24 ocorrerá a XVII edição do evento [Jornada das Estrelas](/atividades/jornada_das_estrelas/jornada_das_estrelas.qmd).

- Local: [Praça do Observatório a Olho Nu do CCA-UFSCar](/localizacao/localizacao.qmd)
- Data: 18 a 20/06/24
- Horários: 19h às 20h, 20h às 21h e 21h às 22h 

Nesta edição teremos:

- Observação do céu com telescópios.
- Visitação ao Observatório a Olho Nu.
- Passeio pelos planetas do Sistema Solar em escala de tamanhos e distâncias.

Cada uma das três atividades terá duração entre 20 e 25 minutos, fazendo com que o circuito completo seja realizado em até 1 hora e 10 minutos. Como as atividades são realizadas à noite e a céu aberto, recomendamos que os visitantes venham agasalhados.

O evento é gratuito e o público geral pode comparecer sem agendamento. Entretanto, as **escolas precisam fazer a solicitação de agendamento** conforme instruções abaixo.

Recebemos a informação do TCA que, nos dias do evento, a linha de ônibus [Linha 0403 - Parque das Arvores / Jardim Alvorada - Carro 820](https://www.smtca.sp.gov.br/wp-content/uploads/2023/01/LINHAS-E-HORARIOS-DE-ONIBUS-SITE-2023-01-30.pdf) estará operando.

## Instruções para as escolas

- Escolas que queiram trazer seus alunos deverão, obrigatoriamente, fazer o agendamento do dia e horário de visitação preenchendo o [formulário abaixo](#form_escolas) e enviando a solicitação gerada para o email observe@ufscar.br.
- O agendamento poderá ser feito até o dia 14 de junho. As escolas que não puderem vir deverão cancelar o agendamento com antecedência para liberar horário para outras escolas.
- Serão aceitos no máximo 4 grupos de 50 alunos por horário. Para cada grupo, deverá haver, obrigatoriamente, pelo menos um professor responsável. Uma mesma escola poderá vir com mais de um grupo desde que haja pelo menos um professor diferente para cada grupo em um mesmo horário.
- As escolas que vierem com grupos que não tiverem sido agendados e confirmados não poderão participar do evento. Todas as escolas serão contatadas por e-mail ou telefone para confirmação do agendamento. Ou seja, não basta fazer o agendamento, é necessário que a escola receba a confirmação por email para poder participar.
- Escolas que chegarem atrasadas em relação ao horário agendado poderão perder alguma das atividades acima, sendo direcionadas para a atividade seguinte desde que dentro do período agendado.	
- Para a UFSCar é uma grande satisfação receber as escolas no evento, trazendo uma grande motivação para que ele ocorra anualmente. Entretanto, as escolas que descumprirem com as informações aqui descritas não poderão participar do evento. Isso é necessário para que as atividades ocorram de forma proveitosa para todos.

## Formulário para as escolas {#form_escolas}


```{=html}
<form id="formulario">
   <p><div class="form-group">
        <label for="escola">Escola</label>
        <input type="text" class="form-control" id="escola" placeholder="Insira o nome da escola">
    </div></p> 
   <p><div class="form-group">
        <label for="municipio">Município</label>
        <input type="text" class="form-control" id="municipio" placeholder="Insira o nome do município da escola">
    </div></p> 
    <div id="grupos"></div>
   <p><button type="submit" class="btn btn-warning">Gerar solicitação</button></p>
   <p><label for="solicitacao">Solicitação</label>
        <textarea class="form-control" id="solicitacao" rows="3" readonly></textarea>
   </p> 
</form>

<script defer>
    const nulo = '---';
    const horarios = [ 
        '19h às 20h',
        '20h às 21h',
        '21h às 22h',
    ];
    const dias = ['18/06','19/06','20/06'];
    const alunos = {
        label: "Quantidade de alunos",
        options: [
            nulo,
            'menos que 15',
            'entre 15 e 30',
            'entre 30 e 50'
        ]
    };
    const escolaridade = {
        label: "Escolaridade",
        options: [
            nulo,
            'Infantil',
            'Fundamental 1',
            'Fundamental 2',
            'Ensino Médio',
            'EJA',
            'Superior',
            'Misto'
        ]   
    };
    const agendamentos = [
        {escola:'INSA', professor:'Cintia', dia:'19/06', horario:'19h às 20h', escolaridade:'Fundamental 1', alunos: 'entre 30 e 50'},
        {escola:'INSA', professor:'Karine', dia:'19/06', horario:'19h às 20h', escolaridade:'Fundamental 1', alunos: 'entre 30 e 50'},
        {escola:'COOPEL', professor:'Isabel', dia:'19/06', horario:'19h às 20h', escolaridade:'Ensino Médio', alunos: 'entre 30 e 50'},
        {escola:'UFSCar', professor:'Samantha', dia:'19/06', horario:'20h às 21h', escolaridade:'Misto', alunos: 'menos que 15'},
        {escola:'Maria Rosa', professor:'Edenilze', dia:'20/06', horario:'19h às 20h', escolaridade:'Ensino Médio', alunos: 'entre 30 e 50'},
        {escola:'Maria Rosa', professor:'Guilherme', dia:'20/06', horario:'19h às 20h', escolaridade:'Ensino Médio', alunos: 'entre 30 e 50'},
        {escola:'Maria Rosa', professor:'Valdezir', dia:'20/06', horario:'19h às 20h', escolaridade:'Ensino Médio', alunos: 'entre 30 e 50'},
        {escola:'Maria Rosa', professor:'Daniele', dia:'20/06', horario:'20h às 21h', escolaridade:'Ensino Médio', alunos: 'entre 30 e 50'},
        {escola:'C.E. Sagrada Família', professor:'Jonathan', dia:'20/06', horario:'20h às 21h', escolaridade:'Ensino Médio', alunos: 'menos que 15'},
        {escola:'NFP/UFSCar', professor:'Victor', dia:'20/06', horario:'20h às 21h', escolaridade:'Superior', alunos: 'menos que 15'},
    ];

    const Ngrupos = 6;

    const evento = 'XVII Jornada das Estrelas';

    const professor = {
        label: "Professor(a)",
        placeholder: "Professor(a) responsável por acompanhar os estudantes"
    }
    const telefone = {
        label: "Telefone",
        placeholder: "Telefone para contato em caso de necessidade"
    }

    const datas = genDatasDisponiveisLista(agendamentos, dias, horarios);

    let grupos = document.getElementById("grupos");
    for (let i = 1; i < Ngrupos+1; i++) {
        let botaoHTML = fromHTML(`<p><button type="button" class="btn btn-primary btn-block" data-bs-toggle="collapse" href="#grupo${i}">Grupo ${i}</button></p>`);
        grupos.append(botaoHTML);
        let divHTML = fromHTML(`<div id="grupo${i}" class="collapse"></div>"`);
        let professorHTML = genInput(`professor${i}`, divHTML, 'text', professor.label, professor.placeholder);
        let telefoneHTML = genInput(`telefone${i}`, divHTML, 'text', telefone.label, telefone.placeholder);
        let alunosHTML = genSelect(`alunos${i}`, divHTML, alunos.options, alunos.label); 
        let escolaridadeHTML = genSelect(`escolaridade${i}`, divHTML, escolaridade.options, escolaridade.label); 
        let opcao1HTML = genSelect(`opcao${i}1`, divHTML, datas, 'Opção 1'); 
        let opcao2HTML = genSelect(`opcao${i}2`, divHTML, datas, 'Opção 2'); 
        grupos.append(divHTML);
    };  

    function genDatasDisponiveisLista(agendamentos, dias, horarios, maxGrupos = 3) {
        let datas = {};
        for (let d of dias) {
            let h = {};
            for (let hx of horarios) h[hx] = 0;
            datas[d] = h;
        }
        for (let a of agendamentos) datas[a.dia][a.horario]++;
        let datasDispo = [nulo];
        for (let d of dias) for (let hx of horarios) if (datas[d][hx] < maxGrupos) datasDispo.push(d + ' - ' + hx);
        return datasDispo;
    }

    function formSubmit(event) {
        event.preventDefault();
        let el = event.target.elements;
        let x0 = ``;
        let x = ``;
        if (el.escola.value == "") return alert("Insira o nome da Escola.");
        else {
            x0 = 
`Prezados organizadores da ${evento},

Nós, da instituição ${el.escola.value}, localizada no município de ${el.municipio.value}, gostaríamos de solicitar o agendamento para participação no evento nas seguintes datas:`
        }; 
        for (let i = 1; i < Ngrupos+1; i++) {
            if (el[`professor${i}`].value != "" &&
                el[`telefone${i}`].value != "" &&
                el[`alunos${i}`].value != nulo &&
                el[`opcao${i}1`].value != nulo) 
            {
                x += 
`

Grupo ${i}:
- Professor responsável: ${el[`professor${i}`].value}
- Telefone: ${el[`telefone${i}`].value}
- Número de alunos: ${el[`alunos${i}`].value}
- Escolaridade: ${el[`escolaridade${i}`].value}
- 1ª opção: ${el[`opcao${i}1`].value}
- 2ª opção: ${el[`opcao${i}2`].value}`;
            }
        }
        if (x == "") return alert("Informe os dados de pelo menos um grupo de alunos.");
        else {
            el.solicitacao.value = x0 + x;
            navigator.clipboard.writeText(x0+x);
            document.getElementById('solicitacao').setAttribute('rows', '20');  
            return alert("A solicitação foi copiada para a área de transferência. Cole-a no corpo do email e envie para oberve@ufscar.br");
        }
    }
    document.getElementById("formulario").addEventListener("submit", formSubmit);

    function genSelect(id, parentHTML, optionsList, label = "", paragraph = true) {
        let selectHTML = fromHTML(`<select class="form-select" id="${id}"></select>`);
        for (option of optionsList) {
            let optHTML = fromHTML(`<option>${option}</option>`);
            selectHTML.append(optHTML);
        }
        if (label != "") {
            let labelHTML = fromHTML(`<label for="${id}">${label}</label>`);
            parentHTML.append(labelHTML);
        }
        if (paragraph) {
            let parHTML = fromHTML('<p></p>');
            parHTML.append(selectHTML);
            parentHTML.append(parHTML);
        }
        else parentHTML.append(selectHTML);
    }

    function genInput(id, parentHTML, type, label = "", placeholder = "", paragraph = true) {
        let inputHTML = fromHTML(`<input type="${type}" class="form-control" id="${id}" placeholder="${placeholder}">`);
        if (label != "") {
            let labelHTML = fromHTML(`<label for="${id}">${label}</label>`);
            parentHTML.append(labelHTML);
        }
        if (paragraph) {
            let parHTML = fromHTML('<p></p>');
            parHTML.append(inputHTML);
            parentHTML.append(parHTML);
        }
        else parentHTML.append(inputHTML);
    }

    function fromHTML(html, trim = false) {
        html = trim ? html.trim() : html;
        if (!html) return null;

        const template = document.createElement('template');
        template.innerHTML = html;
        const result = template.content.children;

        if (result.length === 1) return result[0];
        return result;
    }

</script>
```

::: {.callout-note}
## Atenção
A solicitação não é enviada automaticamente. É necessário que você envie manualmente o texto de solicitação de agendamento para o email observe@ufscar.br
:::

## Agendamentos confirmados

```{=html}
<div id="tabelaAgendamentos"></div>

<script>
    var tableAgen = new Tabulator("#tabelaAgendamentos", {
        layout:"fitColumns",
        groupBy:["dia","horario"],
        data: agendamentos,
        columns:[
            {field:'escola', title:'Escola'},
            {field:'alunos', title:'Alunos'},
            {field:'escolaridade', title:'Nível'},
            {field:'professor', title:'Prof(a)'},
        ],
    });
</script>
```